### PR TITLE
Keep trying to claim in tests

### PR DESCRIPTION
**Pull request by eric**
Don't give up trying to claim new work if claim returns nil. Only give up once
a deadline has passed.

This is related to #82 and has more detail in #80.

### CODE REVIEW

**Comment by eric** [comment]
This does not yet address #75, but I plan to.

**Comment by eric** [comment]
I've added retries to fix #75.

**Comment by eric** [comment]
I've also added a retry for claim in the node test as well.

**Comment by aphyr** [comment]
BTW, the reliance on timeouts is gonna become an increasing problem in tests. Where possible, we should try to use time-independent tests--blocking on promises instead of doing a read after N seconds.

**Comment by ztellman** [comment]
Just double the timeout, problem solved.

**Comment by eric** [comment]
I agree that the timeouts and such are generally bad, but I think in this case the retries make sense because that will actually be replicating the real logic of clients:

The clients will be re-polling for claims forever, doing work when they get it.

**Pull request merged**
