### PR TITLE
Add slf4j

### PR DESCRIPTION
**Pull request by eric**
Replaces all of the other loggers with a logback-based slf4j logger.

Adds logging to stdout.

We will need to discuss what sort of log tuning should happen and where — It's likely we should set some defaults for the zookeeper stuff in `skuld.logging/init`.

I'm not sure if this is ready to be merged yet, but it's making progress.

### CODE REVIEW

**Comment by michaelklishin** [comment]
Have you considered using [Timbre](https://github.com/ptaoussanis/timbre) instead?

**Comment by joelkuiper** [comment]
Pardon my ignorance but what's wrong with using clojure.logging?

**Comment by michaelklishin** [comment]
`tools.logging` has two problems:
- You still have to deal with usability issues of Java logging libraries from time to time
- It is covered by the paper Clojure Contributor Agreement and follows their (very slow moving) development process. So if you hit an issue, you can expect your patch being merged in a few months.

With Timbre, you all you have to know is how to pass a Clojure map and if you want to contribute a bug fix, you submit a pull request and Peter releases a new version in a few days.

**Comment by aphyr** [comment]
I'm open to either, guys--not an expert on logging by any means. :)

**Pull request merged**
