### PR TITLE
Allow for a nil response

### PR DESCRIPTION
**Pull request by eric**
Right now when a handler responds with a nil, nothing is ever sent back to the
client.

### CODE REVIEW

**Comment by eric** [comment]
I just noticed that the documentation for the handler says that it only accepts non-nil values, so I guess the solution is to just not screw up the handlers. I'll try to remember that...

**Comment by eric** [comment]
@aphyr: Is this interface something that you believe is the right interface for this?

Is there a need for a handler to be able to return nil?

**Comment by aphyr** [comment]
IIRC nil means "Don't send a message as a response", which is something handlers have to be able to do.

**Comment by eric** [comment]
It seems like that logic is also sort of handled [here](https://github.com/eric/skuld/blob/3501a844d45f475f6a8cbe0e34caaddd3b3f67bf/src/skuld/net.clj#L291-L303).

That said, it is inefficient to wait for things to fall through to the fallback logic, so it does seem like there needs to be some way to indicate that a handler is declining to handle something.

I don't think it's intuitive to need to return `{}` instead of `nil` to ensure that something is returned, but I guess the only alternative is to come up with a special symbol like `:decline` that is used to indicate that a handler doesn't want to handle something.

**Pull request closed without merging**
